//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dinokin.ScanlationTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dinokin.ScanlationTools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlphaPolis.
        /// </summary>
        public static string AlphaPolis {
            get {
                return ResourceManager.GetString("AlphaPolis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy. Please await..
        /// </summary>
        public static string BusyPleaseAwait {
            get {
                return ResourceManager.GetString("BusyPleaseAwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComicRIDE.
        /// </summary>
        public static string ComicRIDE {
            get {
                return ResourceManager.GetString("ComicRIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files here....
        /// </summary>
        public static string DropFilesHere {
            get {
                return ResourceManager.GetString("DropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        public static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the address to the chapter..
        /// </summary>
        public static string InsertAddressToChapter {
            get {
                return ResourceManager.GetString("InsertAddressToChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL used for this ripper is invalid..
        /// </summary>
        public static string InvalidUrlInserted {
            get {
                return ResourceManager.GetString("InvalidUrlInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPG.
        /// </summary>
        public static string JPG {
            get {
                return ResourceManager.GetString("JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file with a supported image format were found..
        /// </summary>
        public static string NoSupportedImageFormatFound {
            get {
                return ResourceManager.GetString("NoSupportedImageFormatFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a function..
        /// </summary>
        public static string PleaseSelectFunction {
            get {
                return ResourceManager.GetString("PleaseSelectFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an output format..
        /// </summary>
        public static string PleaseSelectOutputFormat {
            get {
                return ResourceManager.GetString("PleaseSelectOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an output path..
        /// </summary>
        public static string PleaseSelectOutputPath {
            get {
                return ResourceManager.GetString("PleaseSelectOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG.
        /// </summary>
        public static string PNG {
            get {
                return ResourceManager.GetString("PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSD.
        /// </summary>
        public static string PSD {
            get {
                return ResourceManager.GetString("PSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize by Percentage.
        /// </summary>
        public static string ResizeByPercentage {
            get {
                return ResourceManager.GetString("ResizeByPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rippers.
        /// </summary>
        public static string Rippers {
            get {
                return ResourceManager.GetString("Rippers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed successfully..
        /// </summary>
        public static string TaskCompletedSuccessfully {
            get {
                return ResourceManager.GetString("TaskCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent Border Remover.
        /// </summary>
        public static string TransparentBorderRemover {
            get {
                return ResourceManager.GetString("TransparentBorderRemover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webtoon Page Joiner.
        /// </summary>
        public static string WebtoonPageJoiner {
            get {
                return ResourceManager.GetString("WebtoonPageJoiner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Young Ace UP.
        /// </summary>
        public static string YoungAceUP {
            get {
                return ResourceManager.GetString("YoungAceUP", resourceCulture);
            }
        }
    }
}
